name: Build Wheel and Publish on Github-Release

on:
  push:
    tags:
      - 'v-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and Install python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"

      - name: Check Version
        id: check_version
        run: |
          TAG_VER=$( echo ${{ github.ref_name }} | sed 's/^v-//' )
          PROJ_VER=$( uv run python -c "import tomllib;print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])" )
          if [ "$PROJ_VER" != "$TAG_VER" ]; then
            echo "âŒ Version mismatch detected! TAG_VER-'$TAG_VER' != PROJ_VER-'$PROJ_VER'"
            exit 1
          fi
          echo "VERSION=${TAG_VER}" >> $GITHUB_ENV

      - name: Build with uv
        run: uv build --no-sources

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl
          tag_name: ${{ github.ref }}
          name: ${{ env.VERSION }}
